apiVersion: v1
kind: Service
metadata:
  name: myapi
  labels:
    app: fast-api
spec:
  type: LoadBalancer
  ports:
  - nodePort: 32334
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: fast-api
